### ISSUE TITLE
esformatter config

### ISSUE THREAD

**Issue by rwwagner90** [DockYard/eslint-plugin-ember-suave#10]
What do you guys use at DockYard for auto formatting your code? I'd love to have an esformatter config or similar that would allow me to just have my code adhere to these rules on save. Does anything like that exist? If not, I may try to create something.

**Comment by brzpegasus** [comment]
We don't use anything in particular, but we mostly deal with projects that we build from the ground up following DY's styleguide, using suave to automate.

ESLint has an fix option but not all rules are implemented with an auto fixer.

**Comment by alexlafroscia** [comment]
I've been working on a PR to add `ember lint` as a command that `ember-cli-eslint` provides that also adds `ember lint:fix` (which just runs the ESLint fixer).  If you're interested, you can check out the PR [here](https://github.com/ember-cli/ember-cli-eslint/pull/93).

**Comment by rwwagner90** [comment]
@alexlafroscia I'd be interested to see what cases ESLint can and cannot automatically fix. We may be able to enforce some with esformatter or something else if needed. Have you run into any gotchas yet?

**Comment by alexlafroscia** [comment]
ESLint fixes are pretty limited, to be honest, although I've never tried to implement a fixer myself.  They recommend to keep them pretty limited.  I think this is something they're actively working on though, I heard mentioned somewhere that they might adopt a CST instead of an AST to make applying changes easier.

**Comment by rwwagner90** [comment]
Going to close this in favor of waiting and using @alexlafroscia's lint fix in the future
