### ISSUE TITLE
Prefer destructuring

### ISSUE THREAD

**Issue by rwwagner90** [DockYard/eslint-plugin-ember-suave#13]
Is it really the intent of the rule to require me to change this:

```js
let staff = model.single;
```

into this:

```js
let { single: staff } = model;
```

Feels less readable to me, so wanted to make sure the rule was functioning as intended.

**Comment by brzpegasus** [comment]
No, that was the bug we uncovered with the tests (remember the comment about destructuring in the for loop?).

**Comment by brzpegasus** [comment]
https://github.com/DockYard/eslint-plugin-ember-suave/pull/11#discussion_r72715856

**Comment by rwwagner90** [comment]
What is prefer destructuring supposed to actually enforce?

**Comment by brzpegasus** [comment]
It's for when you have `let foo = obj.foo`, but it should not error when the variable name is different from the prop name.

**Comment by alexlafroscia** [comment]
I'll include this in my PR for #16
