### ISSUE TITLE
Space after `*` in function generator is incorrectly configured

### ISSUE THREAD

**Issue by brzpegasus** [DockYard/eslint-plugin-ember-suave#15]
This is a limitation of the `generator-star-spacing` rule in ESLint. See https://github.com/eslint/eslint/issues/6777.

Essentially, we need to allow for the following:

```js
function* foo() {}

let bar = function*() {};
```

The rule should be updated upstream, or we need to patch it up here temporarily.

**Comment by rwwagner90** [comment]
Still waiting for ESLint folks to decide if they want to support this or not. Doesn't seem to be a high priority, and I suspect we'll have to do the fixing, even if they give it the thumbs up. @alexlafroscia think you could write another custom rule to support this and we could use our custom one instead of relying on the built in ESLint one?

**Comment by brzpegasus** [comment]
This is definitely not high priority by any means.

**Comment by rwwagner90** [comment]
@brzpegasus yeah, agreed, just wanted to try to wrap everything up. I hate to get 99% of the way there and stop 😛

**Comment by alexlafroscia** [comment]
Yeah, I can make a modified version of the default rule if that's what we need.

**Comment by rwwagner90** [comment]
@alexlafroscia we may not really care, as this seems like a small issue, but I'll leave that up to @brzpegasus and the DockYard folks.

**Comment by alexlafroscia** [comment]
For me personally, I don't use generator functions, but I also don't mind fixing this temporarily in-repo until we can fix it upstream.  Good practice on making ESLint rules :)

**Comment by alexlafroscia** [comment]
Realized that with other projects, I don't really have time to take this on -- especially since I'm not someone that uses generators day-to-day.

I made a branch and pushed it here that starts the work by pulling in the existing `generator-start-spacing` rule as a starting place.

**Comment by rwwagner90** [comment]
@alexlafroscia no worries, I don't use generators either, so I'm fine with waiting on ESLint to say yay or nay here. @brzpegasus any chance of just not enforcing spacing at all for generator stars being okay with you guys?
