### ISSUE TITLE
Finish porting missing rules to ESLint

### ISSUE THREAD

**Issue by alexlafroscia** [DockYard/eslint-plugin-ember-suave#2]
The following JSCS rules are not provided by `ember-suave` or `ember-deprecations`, and also are not directly provided by ESLint.  They may be related to existing rules, but [Polyjuice](https://www.npmjs.com/package/polyjuice) did not convert them automatically.

- [x] `requireArrayDestructuring`
- [ ] `requireBlocksOnNewline`
- [ ] `requireNumericLiterals`
- [x] `requireObjectDestructuring`
- [ ] `requireSpaceBetweenArguments`
- [ ] `requireSpacesInConditionalExpression`
- [ ] `requireSpacesInForStatement`
- [ ] `validateParameterSeparator`

**Comment by alexlafroscia** [comment]
Destructing rules added in 8df47b2df61df5560104b6a0b0ff18a18a732688

**Comment by rwwagner90** [comment]
@alexlafroscia `requireBlocksOnNewLine` just means no single line blocks like `function() {}` right? If I understood it correctly, can't we use this to do ESLint? http://eslint.org/docs/rules/brace-style#stroustrup

**Comment by rwwagner90** [comment]
Also, for `requireSpaceBetweenArguments` what about this? http://eslint.org/docs/rules/comma-spacing

**Comment by rwwagner90** [comment]
And for `requireSpacesInForStatement` can we use this?  http://eslint.org/docs/rules/semi-spacing

**Comment by alexlafroscia** [comment]
Yeah, definitely to all of those.  We just need to come up with the right configuration for each of them to match the right style.  If you want to do that, that would be super helpful -- the JSCS Suave repo has tests for each of them that we can use as a reference.

**Comment by alexlafroscia** [comment]
Maybe it's even worth adding tests for the built-in rules to verify that the configuration is what we think it is.

**Comment by rwwagner90** [comment]
@alexlafroscia so should I just add the rules to config/recommended and see if they work as intended? Sorry just jumping into this and haven't done much with setting up ESLint plugins before. Also, would you be opposed to alphabetizing the rules? Makes it a lot easier to see which ones are already in there. I can do that as I go if you are cool with it.

**Comment by brzpegasus** [comment]
The good part about all the tests in `ember-suave` is that we were able to test whether the configuration was correct. So in a way, we weren't unit testing each rule, but rather running code snippets against the entire config to verify if they would pass or fail, which was extremely useful.

Ideally we would have something like that here as well, rather than check manually (would prevent regressions as well).

**Comment by rwwagner90** [comment]
@alexlafroscia this rule is currently already in the rules:

```
'semi-spacing': ['error', {
      'before': false,
      'after': true
    }],
```

This takes care of `requireSpacesInForStatement`. I checked it at http://eslint.org/demo/ to be sure.

**Comment by rwwagner90** [comment]
@brzpegasus I think the majority of these are potentially handled already, so I suppose the real issue here is not to implement these, but to write some tests to ensure they all work and no regressions arise? I noticed the only tests in the repo are for the custom rules. If we can come up with an accepted format for testing, I would be glad to port some/all of the tests over.

**Comment by brzpegasus** [comment]
Yeah, I think the tests would help reveal which rules are misconfigured and which ones we've missed, so I would see that as the first step to move this forward.

`ember-suave` made use of broccoli for the tests, since it was built on top of `broccoli-jscs`. It then parsed out the test results to look for pass/fail output. It might make sense to run code snippets through the eslint engine itself and see if we get what we expect to get. I can look into this more.

**Comment by rwwagner90** [comment]
@brzpegasus if you can figure out the setup, I don't mind doing the work to test each scenario.

**Comment by rwwagner90** [comment]
@brzpegasus were you able to look into the setup of how we want to go about writing tests? I can take a stab at it, if you would like. Just would really love to have ESLint and Suave playing together nicely as soon as we can 😃

**Comment by brzpegasus** [comment]
@rwwagner90 I have a WIP PR. It's getting close! I just have a small thing to figure out to properly load in custom rules (FYI, my OSS schedule is a bit sporadic. Some days I can get more in than others).

In the meantime, you're welcome to steal the config from this repo and put it in your own project's `.eslintrc.js` (just make sure to install `ember-cli-eslint`), as well as tweak to your liking or per the styleguide of your team. The custom rules should be functional if you wish to use them immediately.

**Comment by rwwagner90** [comment]
@brzpegasus aren't the custom rules already tested right now, but not the buillt in ones? Let me know if there is anything you'd like me to help with.

**Comment by brzpegasus** [comment]
Yup. They are unit tested, just like the built-in rules are unit tested in ESLint itself. What's missing is just the actual config test, which is what my PR tries to solve. It gives us reassurance that the configuration of those rules is as expected, and that all the rules work nicely together -- integration testing so to speak.

**Comment by rwwagner90** [comment]
Ah, okay. I misunderstood. Makes sense 👍

**Comment by brzpegasus** [comment]
#8 puts the framework in place for testing the config. We just need to add the code snippets from `ember-suave` and log issues for misconfigured or missing rules.

**Comment by rwwagner90** [comment]
Thanks @brzpegasus! Want me to start porting some of the test snippets over?

**Comment by brzpegasus** [comment]
Sure, given I most likely won't have too much time until later tonight.

**Comment by rwwagner90** [comment]
I'll start on some now then

**Comment by rwwagner90** [comment]
@brzpegasus is there a reason we can't essentially just copy and paste all the fixtures over? I know they are named for JSCS rules, but I don't know if we care about that?

**Comment by brzpegasus** [comment]
We sure can!

**Comment by rwwagner90** [comment]
Okay, great. I'll just copy them over then 😄

**Comment by rwwagner90** [comment]
@alexlafroscia @brzpegasus now that we have the majority of the rules and tests copied over and passing, can we delete this issue? It appears we are handling these now, and we are now tracking the few left as separate issues.

**Comment by alexlafroscia** [comment]
Yup, after getting the whole fixture test suite ported over and passing I think we're good here!
