### ISSUE TITLE
Add recommended

### ISSUE THREAD

**Issue by rwwagner90** [DockYard/eslint-plugin-ember-suave#20]
If we are going with recommended, shouldn't we add back the extend added by ember-cli-eslint to the README?

**Comment by alexlafroscia** [comment]
I thought the idea was that the recommended config we provide here is in lieu of the one that `ember-cli-eslint` provides?  It's really just the recommended config with a few little tweaks to be ES6-friendly

**Comment by alexlafroscia** [comment]
Actually no, I see that we don't include `eslint:recommended` in our config right now.  I think we should probably just extend our config from the ESLint recommended one, since we already include all of the additional configuration that `ember-cli-eslint` provides.

**Comment by brzpegasus** [comment]
Yeah, I was going to do that but our tests started failing because of `no-unused-vars` rules and such in our fixtures :p. Haven't quite had time to work on it yet.

**Comment by alexlafroscia** [comment]
@brzpegasus I can take a look tonight if you'd like
