### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by alexlafroscia** [DockYard/eslint-plugin-ember-suave#21]
Right now, the installation instructions in the README are just what the Yeoman generator provided when I made the repo.  We should add a section about getting things going in the Ember CLI through `ember-cli-eslint` too.

**Comment by rwwagner90** [comment]
@alexlafroscia shouldn't we just actually convert ember-suave to use ESLint and this plugin and then people can just `ember install ember-suave`?

**Comment by alexlafroscia** [comment]
I don't think so. `ember install` should be kept for Ember addons, which this really isn't.  I personally don't think this project should break from the ESLint community convention of plugins being called `eslint-plugin-foo`, but I guess it's up to the Dockyard folks on whether or not they want to change it.  My vote goes in favor of this simply being an ESLint plugin since that's really all it is.

**Comment by rwwagner90** [comment]
@alexlafroscia but I'm not talking about this plugin being ember installed, I am talking about switching ember-suave itself over to using this. ember-suave right now can be ember installed, and it just adds the JSCS preset to your jscsrc. I'm advocating for doing the same with ESLint. This plugin would still be consumed as a normal ESLint plugin, just setup for you.

**Comment by alexlafroscia** [comment]
What would `ember-suave` do then? Right now, Suave is not just adding the JSCS configuration but also doing the JSCS evaluation on the code.  The Ember community already has an ESLint addon, so `ember install ember-suave` would just install this other dependency?

**Comment by rwwagner90** [comment]
I would have ember-suave do a `addAddonToProject` and add ember-cli-eslint, then `addPackageToProject` and add this plugin and extend it, I think. Basically just would like there to be one install to set it all up, as it is tailored specifically to ember.

**Comment by alexlafroscia** [comment]
Hmm, that's interesting.  I feel a little weird defining a dependency simply because you want to run the installation script, and then could effectively remove it from your project again.  I'd love to hear some thoughts from @rwjblue or @stefanpenner on addons being used that way.

**Comment by rwwagner90** [comment]
@alexlafroscia it's essentially the same as any library wrapper addons out there that just provide shims to import those libraries. I like to make setup as easy as possible for the user, but installing a couple things and changing a couple lines manually in a config is not a big deal I suppose. Just really would like to `ember install ember-suave` and be good to go, as isn't that how it works now? One install and it just works?

**Comment by alexlafroscia** [comment]
Yup, definitely how it works now.  Like I mentioned earlier, though, the current `ember-suave` package does more than just installing JSCS and the configuration, it also provides the linter to Ember to actually run the validation against the Broccoli nodes.  In this case, `ember-cli-eslint` provides that already, so the actual `ember-suave` package would *only* serve to install and configure other dependencies.  I'm not saying that's bad or wrong, I'm just saying it's unusual.
