### ISSUE TITLE
Remove babel-eslint parser

### ISSUE THREAD

**Issue by brzpegasus** [DockYard/eslint-plugin-ember-suave#24]
We should remove the parser from the config (and default to Espree), to stay in line with recommendations from ember-cli-eslint.

**Comment by cibernox** [comment]
Also, I want to let you know that because a problem in ESLint, babel-parsed in NPM2 is not installed in the place ESLint expects and therefore it can find it. 
This lead to a pretty infuriating debugging session because it failed in circle-ci but ran locally.
