### ISSUE TITLE
Why not an addon?

### ISSUE THREAD

**Issue by bcardarella** [DockYard/eslint-plugin-ember-suave#30]
Unless I'm missing something, this is meant only for ember apps. If so, then why not make this an addon and have it its install template also install `ember-cli-eslint` so the extra setup process isn't necessary?

**Comment by brzpegasus** [comment]
It has to follow the structure and naming conventions of an ESLint plugin (NPM package named `eslint-plugin-<plugin_name>` and specific export object) for it to be discoverable and recognized as a plugin by the ESLint engine.

If we wanted to reduce install steps, we can still re-utilize `ember-suave` but its only existence would be to do the one-time npm install of `ember-cli-eslint` and npm install of this plugin as well. Basically, this repo still needs to exist.

**Comment by bcardarella** [comment]
Gotcha, makes sense.
