### ISSUE TITLE
new-cap exception for `Handlebars.SafeString`

### ISSUE THREAD

**Issue by MatrixZ** [DockYard/eslint-plugin-ember-suave#35]
When I use `Handlebars.SafeString`, I get the below error.

> A function with a name starting with an uppercase letter should only be used as a constructor  new-cap

**Comment by brzpegasus** [comment]
You are supposed to instantiate with `new`, e.g. `new Handlebars.SafeString()`. Better yet, use `Ember.String.htmlSafe()` instead. See this [issue](https://github.com/emberjs/ember.js/issues/13191).
