### ISSUE TITLE
Can't run `eslint`

### ISSUE THREAD

**Issue by btecu** [DockYard/eslint-plugin-ember-suave#36]
Once this plugin is installed and configured according to instructions, `eslint` command no longer works:
`Cannot find module 'eslint-plugin-ember-suave'`.

Is there an alternative solution to reference the project?

**Comment by alexlafroscia** [comment]
You need to have ESLint plugins installed within the same context as the `eslint` executable. For example, if you are running ESLint from a local dependency, like:

```bash
./node_modules/.bin/eslint
```

then you need to have `eslint-plugin-ember-suave` installed in the local project.  However, is ESLint is being run as a "global" executable, like:

```bash
eslint
```

then you need to have `eslint-plugin-ember-suave` installed globally:

```bash
npm install -g eslint-plugin-ember-suave
```

That's not something specific to this plugin; all ESLint plugins work that way.

**Comment by btecu** [comment]
Thanks @alexlafroscia, I didn't think about trying that.
