### ISSUE TITLE
using Ember.Test.registerAsyncHelper causes undef failures

### ISSUE THREAD

**Issue by bcardarella** [DockYard/eslint-plugin-ember-suave#46]
We can use: http://emberjs.com/api/classes/Ember.Test.html#method_registerAsyncHelper

to register new test helpers. The eventual outcome of this function is to register the function on `window`: https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-testing/lib/ext/application.js#L118

so that you can call your custom function without having to import it.

the problem is that suave is not aware of this because the function is assigned to window at the run-time of the test suite, not at build time. The test fails with `undef` errors

**Comment by bcardarella** [comment]
The solution is to add these functions to the global rules

**Comment by brzpegasus** [comment]
Right, the linter doesn't inspect the `window` object to see what properties (in this case, async helpers) are registered on it. It only looks at the AST that's generated from a given source file, so that data isn't available then.

You can specify those in the `tests/.eslintrc.js` file in a `globals` hash:

```js
// tests/.eslintrc.js

module.exports = {
  env: {
    embertest: true
  },
  globals: {
    // Specify globals with a value of `true` or `false`:
    // `false` will make it read-only
    // `true` will allow the variable to be reassigned
    clickLink: false,
    anotherCustomHelper: false
  }
};
```

**Comment by rwjblue** [comment]
TBH, I would actually suggest importing them instead of relying on the global.

**Comment by rwjblue** [comment]
Something like https://github.com/ember-a11y/ember-a11y-testing/blob/master/addon-test-support/audit.js#L30

**Comment by rwjblue** [comment]
This way importing the module forces the registerHelper / registerAsyncHelper invocation to be called (and therefore the acceptance test helper is created), but also export a function that just defers to `window.whatever(...arguments)`.  This avoids having to add global and makes it much clearer where thisnmagical global function comes from...

**Comment by brzpegasus** [comment]
I'd be totally in favor of that!

**Comment by bcardarella** [comment]
@rwjblue does the grand testing RFC move away from these globals in favor of import all the things?

**Comment by brzpegasus** [comment]
There's a section on [test helpers](https://github.com/rwjblue/rfcs/blob/1ede9e34eebaca147cd1d6914ed002c34896c107/text/0000-grand-testing-unification.md#registering-custom-test-helpers) in that RFC, which talks about moving toward a module solution.
