### ISSUE TITLE
Enforce line break between blocks/functions

### ISSUE THREAD

**Issue by brzpegasus** [DockYard/eslint-plugin-ember-suave#49]
Example:

```js
// Bad
init() {
},
foo() {
},
bar() {
},
actions: {
  anAction() {
  },
  anotherAction() {
  }
}
```

```js
// Good
init() {
},

foo() {
},

bar() {
},

actions: {
  anAction() {
  },

  anotherAction() {
  }
}
```

**Comment by Serabe** [comment]
Only as properties of an object? I mean, do you want to enforce it after if / loop statements? Or only for properties of objects / classes?

**Comment by Serabe** [comment]
[lines-between-class-members](https://eslint.org/docs/rules/lines-between-class-members) `["error", "always", { exceptAfterSingleLine: true }]`
[padding-line-between-statements](https://eslint.org/docs/rules/padding-line-between-statements) with some configuration.
