### ISSUE TITLE
Audit rules `eslint:recommended`

### ISSUE THREAD

**Issue by brzpegasus** [DockYard/eslint-plugin-ember-suave#5]
The README recommends extending `./node_modules/ember-cli-eslint/coding-standard/ember-application.js` as well, which extends `eslint:recommended`. We need to make sure those rules are well aligned with `ember-suave`'s styleguide.

**Comment by alexlafroscia** [comment]
I left that in there because it will automatically be in there based on what `ember-cli-eslint` generates by default.  The case might be that removing that configuration altogether is actually the better way to go.

**Comment by brzpegasus** [comment]
Yes, I agree, though we'll have to carry over some of the other ES6-related config if we do (and I think the base `tests/.eslintrc.js` from `ember-cli-eslint` has some extra stuff too.

**Comment by brzpegasus** [comment]
There are rules from `eslint:recommended` I do want to add though, like :skull: to `console.log()`! But that can be for later.

**Comment by rwwagner90** [comment]
I'm still just using the ember-cli-eslint recommended ones and extending the ember-suave plugin as well. Not sure if any of that clashes with the DockYard style or not. If it does, I'd be glad to port some of the rules over from recommended to here.

**Comment by rwwagner90** [comment]
@brzpegasus are there any other rules from recommended you wanted to port over? I personally am a fan of just extending ember-cli-eslint's recommended as well, but I would be glad to help with the effort to port more rules over, if you'd like me to.

**Comment by brzpegasus** [comment]
I'm going to close this. Everything in `eslint:recommended` is :+1:.
