### ISSUE TITLE
What's the purpose of config/base.js?

### ISSUE THREAD

**Issue by edouard-lopez** [DockYard/eslint-plugin-ember-suave#52]
From what I understand `base.js` is required in [`recommended.js`](https://github.com/DockYard/eslint-plugin-ember-suave/blob/19911fbdc7a4087ba17dee80c9342f021ddb33a4/config/recommended.js#L13). 

Could you elaborate on the use-case of each file?

**Comment by brzpegasus** [comment]
The idea was that if we ever wanted this library to expose multiple configuration files, e.g. one for Ember, one for use in Node, they could still share the same subset of rules defined in `base.js`. In practice, we haven't gone that route yet and the name of the repo unnecessarily suggests it could only be used on Ember projects. This [issue](https://github.com/DockYard/eslint-plugin-ember-suave/issues/51) discusses the latter.
