### ISSUE TITLE
new modules api

### ISSUE THREAD

**Issue by asantos00** [DockYard/eslint-plugin-ember-suave#54]
Hi!

Guys, do we plan to do something like this https://github.com/ember-cli/eslint-plugin-ember/issues/86 ? As the new version of ember recommends this import syntax, I think it makes sense... (even if it is not activated on the default configuration)

Thanks

**Comment by brzpegasus** [comment]
Absolutely! 👍

**Comment by asantos00** [comment]
It is already done in another awesome ember lint plugin. https://github.com/ember-cli/eslint-plugin-ember.

Is there a way we can add the rule without just copying it? If there is none, I will give credits to them and just add this rule here, otherwise I'm more than happy to follow your suggestions

Rule code: https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/new-module-imports.js

**Comment by brzpegasus** [comment]
@asantos00 Yup, the intention was not to duplicate the rule, but to reference it in our default config.

**Comment by asantos00** [comment]
Dumb question: Can we just add the `new-module-imports` rule at our default config without having the rule implemented? 

Since we are not extending https://github.com/ember-cli/eslint-plugin-ember I don't know how to do it :/
