### ISSUE TITLE
Missing rules on update to v2.0.0-beta.1

### ISSUE THREAD

**Issue by fran-worley** [DockYard/eslint-plugin-ember-suave#77]
I'm not quite sure what I'm doing wrong here but since upgrading v1 to v2.0.0-beta.1 ember-suave rules don't seem to be picked up by eslint so we're getting messages like this:

`Definition for rule 'ember-suave/lines-between-object-properties' was not found`
`Definition for rule 'ember-suave/no-direct-property-access' was not found`

Very likely I'm doing something silly but if you've got any pointers that would be awesome!

**Comment by fran-worley** [comment]
So this would be a very silly omission on my part - these rules can only be found if this is added as a plugin in eslintrc!

**Comment by nadnoslen** [comment]
This actually bit me too.  I wonder if we shouldn't add an extra section to the README.md ensuring that if you're adding this manually to your `.eslintrc.js` you must make sure to add the plugin:

```javascript
module.exports = {
  // ...
  plugins: [
    'ember',
    'ember-data-sync-relationships',
    'ember-suave'
  ],
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended',
    'plugin:ember-suave/recommended'
  ],
  // ...
};
```

When I ran the `ember install ember-cli-eslint` it wanted to overwrite my existing `.eslintrc.js` ... that's how ended up on this closed issue.
